"
In what way is read/review a status? Even though it's not explicitly stated in GTD, it seems possible that something could start out as read/review and then become relevant to an active project and therefore worthy of moving to an active status. This feels like Never Doing Now, so we'll handle it the same way.
"
Class {
	#name : #PpReadReviewStatus,
	#superclass : #PpStatus,
	#category : #'ProjectProject-Core-Projects-Support'
}
